n1 = int(input("Enter your single digit number: "))
n2 = int(str(n1)*2)
n3 = int(str(n1)*3)
#print (n1+n2+n3)
print (n1+n2+n3)

#a = int(input("Input an integer : "))
#n1 = int( "%s" % a )
#n2 = int( "%s%s" % (a,a) )
#n3 = int( "%s%s%s" % (a,a,a) )
#print (n1+n2+n3)
